language: node
node:
- "8"
- "6"
- "9"
- "4"
cache: yarn
git:
  depth: 3
jobs:
  include:
  - stage: test
    script: yarn validate-schema
  - stage: deploy
    if: tag IS present
    deploy:
      provider: npm
      email: az@kreatiefer.de
      api_key: $NPM_API_KEY
      on:
        tags: true
        node: "8"
