language: node_js
node_js:
- "8"
- "6"
- "9"
- "4"
cache: yarn
git:
  depth: 3
script:
- yarn validate-schema
deploy:
  provider: npm
  email: az@kreatiefer.de
  api_key: $NPM_API_KEY
  on:
    tags: true
    node: "8"
