language: node_js
node_js:
- "8"
- "6"
- "9"
- "4"
cache: yarn
git:
  depth: 3
script: yarn validate-schema
jobs:
  include:
  - stage: deploy
    if: tag IS present
    node_js: "8"
    deploy:
      provider: npm
      email: az@kreatiefer.de
      api_key: $NPM_API_KEY
